fs = require 'fs'
root = document.documentElement

module.exports =
  activate: (state) ->
    atom.config.observe 'there-will-be-cake-ui.colorScheme', (value) ->
      setColorScheme(value)

    atom.config.observe 'there-will-be-cake-ui.font', (value) ->
      setFont(value)

  deactivate: ->
    unsetColorScheme()
    unsetFont()


# Color Scheme

setColorScheme = (colorScheme) ->
  schemeFile = colorScheme.toLowerCase().replace(/ /g, '-')
  content = "// This file is automatically generated by config.\n@import \"color-schemes/#{schemeFile}.less\";"
  fs.writeFileSync("#{__dirname}/../styles/color-scheme.less", content)
  pack.reloadStylesheets() for pack in atom.packages.getActivePackages()
  pack.reloadStylesheets() for pack in atom.themes.getActiveThemes()

unsetColorScheme = ->
  setColorScheme('strawberry-shortcake')


# Font

setFont = (font) ->
  root.setAttribute('theme-there-will-be-cake-ui-font', font.toLowerCase().replace(/ /g, '-'))

unsetFont = ->
  root.removeAttribute('theme-there-will-be-cake-ui-font')
