fs = require 'fs'

module.exports =
  activate: (state) ->
    console.log("Activated: ", state)
    atom.config.observe 'there-will-be-cake-ui.colorScheme', (value) ->
      setColorScheme(value)

  deactivate: ->
    unsetColorScheme()


# Color Scheme -----------------------

setColorScheme = (colorScheme) ->
  console.log("here")
  schemeFile = colorScheme.toLowerCase().replace(/ /g, '-')
  content = "// This file is automatically generated by config.\n@import \"color-schemes/#{schemeFile}.less\";"
  console.log("Trying to put file: ", content)
  fs.writeFileSync("#{__dirname}/../styles/color-scheme.less", content)

unsetColorScheme = ->
  setColorScheme('strawberry-shortcake')
