fs = require 'fs'

module.exports =
  activate: (state) ->
    atom.config.observe 'there-will-be-cake-ui.colorScheme', (value) ->
      setColorScheme(value)

  deactivate: ->
    unsetColorScheme()


# Color Scheme -----------------------

setColorScheme = (colorScheme) ->
  content = `// This file is automatically generated by config.
  @import "color-schemes/${colorScheme.toLowerCase().replace(/ /g, '-'))}.less";`
  fs.writeFileSync("#{__dirname}/../styles/color-scheme.less", content)

unsetColorScheme = ->
  setColorScheme('strawberry-shortcake')
